### ISSUE TITLE
Content tags for laravel 5

### ISSUE THREAD

**Issue by samiboukadida** [GrahamCampbell/Laravel-Navigation#7]
I have to change content tags from '{{' to '{!!' , every time you make an update.
Thanks.

**Comment by GrahamCampbell** [comment]
I fixed this yesterday actually. :)

**Comment by GrahamCampbell** [comment]
See https://github.com/GrahamCampbell/Laravel-Navigation/commit/2697daeb887c14488b3645c8b2ebcffb6d05c9ee.
