### ISSUE TITLE
Overriding default view/blade

### ISSUE THREAD

**Issue by chintankotadia** [GrahamCampbell/Laravel-Navigation#9]
Is there any way, I can override default bootstrap view in order to use my custom view? 

Thanks! :)

**Comment by GrahamCampbell** [comment]
Yes, publish the package views.

**Comment by niknetniko** [comment]
I might be wrong, but shouldn't the `NavigationServiceProvider.php` file implement the `publishes` method for this to work?

**Comment by GrahamCampbell** [comment]
It doesn't have to.

**Comment by GrahamCampbell** [comment]
It just means we don't auto-publish the view for you. This allows us to push changes without the user having to go and delete the published file to upgrade.

**Comment by niknetniko** [comment]
I see. Thanks!
